src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from students.views import IndexView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.urls import path

from students.views import (
    first_view,
    get_students,
    test,
    CreateStudentView,
    UpdateStudentView,
    UserLogin,
    UserLogout,
    UserRegistration,
    ActivateUser,
    search_history,
)

app_name = "students"

urlpatterns = [
    path("details/", first_view, name="index"),
    path("", get_students, name="get_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>/", UpdateStudentView.as_view(), name="update_student"),
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("registration/", UserRegistration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    # path("send-test-email/", send_test_email, name="send_test_email"),
    path("test/", test, name="test_view"),
    path("history/", search_history, name="history"),
]

# localhost:8000/students/ - all
# localhost:8000/students/12/ - one element
# localhost:8000/students/create/ - create element
# localhost:8000/students/update/12/ - update element
# localhost:8000/students/delete/12/ - delete element

src/templates/index.html
{% load static %}

<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Cover Template · Bootstrap v5.3</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous">

    <link rel="canonical"
          href="https://getbootstrap.com/docs/5.2/examples/cover/">


    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">{{ site_name }}</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link fw-bold py-1 px-0 active" aria-current="page"
                   href="{% url 'index' %}"> Home </a>
                <a class="nav-link fw-bold py-1 px-0" href="{% url 'students:get_students' %}"> Students list </a>
                <a class="nav-link fw-bold py-1 px-0" href="{% url 'students:create_student' %}"> Create </a>

                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    {% if user.is_authenticated and user.avatar %}
                        <img src="{{ user.avatar }}" alt="mdo" class="rounded-circle" width="32" height="32">
                    {% else %}
                        <img src="https://github.com/mdo.png" alt="mdo" class="rounded-circle" width="32" height="32">
                    {% endif %}
                </a>
                <a>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item">{{ user.first_name|title }} {{ user.last_name|title }}</a></li>
                            <li><a class="dropdown-item" href="#">Profile</a></li>
                            <li><a class="dropdown-item" href="#">Change password</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'students:logout' %}">Logout</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'students:login' %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'students:registration' %}">Registration</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Reset password</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'social:begin' 'google-oauth2' %}">Registration
                                via Google</a></li>
                            <li><a class="dropdown-item" href="#">Registration via facebook</a></li>
                        {% endif %}
                    </ul>
                </a>

            </nav>
        </div>
    </header>

    <main class="px-3">
        {% block content %}
            {% if messages %}
                <ul class="message">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}" role="alert">
                          {{ message|safe }}
                          <button type="button" class="btn-close" data-bs-dismiss="alert"
                                  aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </ul>
            {% endif %}
            <h1>Cover your page.</h1>
            <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit
                the
                text, and add your own fullscreen background photo to make it your own.</p>
            <p class="lead">
                <a href="#" class="btn btn-lg btn-light fw-bold border-white bg-white">Learn more</a>
            </p>
            <form method="GET" action="{% url 'students:get_students' %}">
                <div class="input-group mb-3">
                    <input type="text" class="form-control"
                           placeholder="Search students"
                           name="search_text"
                           aria-label="Search students"
                           aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="submit"
                            id="button-addon2">Search
                    </button>
                </div>
            </form>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

            {{ form.media }}
            {{ form }}
            <img src="{% static 'img/meme.jpeg' %}" alt="no image">
        {% endblock content %}
    </main>

{#    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d11726.15838674986!2d{{ user.location.0 }}!3d{{ user.location.1 }}!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1suk!2sua!4v1674685987491!5m2!1suk!2sua"#}
{#            width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"#}
{#            referrerpolicy="no-referrer-when-downgrade"></iframe>#}

    <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</body>
</html>

src/templates/search_history.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
       <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Key</th>
            <th scope="col">Value</th>
        </tr>
        </thead>
        <tbody>
        {% for key, value in search_logs.items %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <th>{{ key }}</th>
                <th>{{ value }}</th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

{% endblock %}